### ISSUE TITLE
Ability to Use ID in slug

### ISSUE THREAD

**Issue by matthewscalf** [spatie/laravel-sluggable#109]
So I love this package. I will say that, but it's come up where a customer now wants the database ID in the url, I tried to convince him otherwise, but they "need" it. The events used for the slug generation happen before the record is saved to the database when creating the record. We only use the creation event. I can think of several ways to make this work but wanted to know if you had any tips to keep it clean and in line with how you've built this package.

**Comment by atymic** [comment]
I've come across this problem in the past as well, and IMO there's no great solution. 

You can either hook the `saved` event, generate the slug and save again (without model events), but this requires an extra database round trip.

Alternatively, you can save the slug without the ID, and use a trait to override the getters and return the slug + id combination. The issue here is finding/querying models by slug gets complex. I added a method on the trait that splits the slug back into slug and ID and finds the model by id, but the disadvantage is you can't use this with the query builder.
