### ISSUE TITLE
Problem with uniqueness and global scopes

### ISSUE THREAD

**Issue by Artessan** [spatie/laravel-sluggable#12]
Hi, I`m working with a db that has defined the slug field like unique, and use softdeletes for deleted info, the problem is that the slug check for unique value in this package don't check softdelete.

Can you help me with this. Thanks and sorry for the english

**Comment by freekmurze** [comment]
Hi, I'm not using softDeletes myself, that's why it isn't included in the package. I'd accept a simple PR that adds this to the package.

**Comment by Artessan** [comment]
HI, Thanks!!!!

**Comment by juniorb2ss** [comment]
You can use boot.
```
protected static function boot() {
    parent::boot();
    static::deleting(function($model) {
       $model->slug = null; // remove slug
       $model->save();
    });
}
```

**Comment by Artessan** [comment]
yeah, that is a option but the problem is that the slug is set to null, then if the model is restored you need set the model to set the slug again in the model, i think is best option add one option in config  to check with softdeleted or not

**Comment by roshangautam** [comment]
I think this is not just a problem with softDeletes but with all global scopes. For instance if I have a global scope for multi tenancy you will still get an error saying "your slug is not unique" if you have a unique constraint forced on your database column. In case you do not have a constraint you will end up having duplicate slugs. The quick and easy solution would be to add a withoutGlobalScopes() in otherRecordExistsWithSlug() method.

**Comment by sebastiandedeyne** [comment]
`otherRecordExistsWithSlug` now does a `withoutGlobalScopes` call.

Gonna close this. There's no right or wrong here, sometime you'll want global scopes (e.g. if you're versioning your model, the slugs are allowed to be the same), sometimes you don't want them (e.g. in the case of soft deletes).

If you're experiencing issues due to global scopes, overwrite the `otherRecordExistsWithSlug` since it's most likely due to something situational.
