### ISSUE TITLE
Request for php 7.3 package which is compatible with Laravel 6

### ISSUE THREAD

**Issue by mrlinnth** [spatie/laravel-sluggable#137]
Not a lot of other laravel packages are ready for php 7.4.

I have been using this [rinvex/laravel-subscriptions](https://github.com/rinvex/laravel-subscriptions) package and it is using sluggable package.

With the latest updates on both packages, I have no option other than switch to php 7.4.
But I have other packages which will break on php 7.4.

So it will be really great if there is a version that work with php 7.3 and laravel 6.

**Comment by freekmurze** [comment]
Version 2.2.1 of this package is installable in PHP 7.3 / Laravel 6

**Comment by mewejo** [comment]
Any chance of a 2.2.2 for Laravel 7 @freekmurze to support PHP 7.3 please?

**Comment by amanpatel** [comment]
I have inherited a really bad EC2 / Amazon Linux setup that has my production system stuck on php 7.3

Obviously I need to dig myself out of this problem, but in the mean time, I needed something that worked with Laravel 8, and with php 7.3 (since laravel 8 does support php 7.3).

I actually got this to work, so I'll fork the code and let you know. Obviously, this isn't a long term solution. So I am not recommending you do this. But if you are in the same boat as me, it might come in handy.
