### ISSUE TITLE
Ability to enable/disable slug generation on demand

### ISSUE THREAD

**Issue by msonowal** [spatie/laravel-sluggable#153]
As I have inspected there is no option to to enable/disable slug generation on demand.

Suppose I have a model which has
```
public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug')
            ->doNotGenerateSlugsOnUpdate();
    }
```

but sometimes I do not want to create the slug so it does not generate the query for checking duplication or generation and we are manually setting it. So thus cases we don't want the slug generation to trigger. Is there any possibility to do it maybe I may have missed. Or if you think it can solved using simple hack I would be glad to make a PR out of it.

**Comment by mallardduck** [comment]
I think if this could be implemented in a manner that applies to both creations and updates that would be great. Essentially just a general method to tell the model to ignore slugs for the current transaction.

**Comment by mallardduck** [comment]
@msonowal

The best - although not great - solution I've found as a bodge of a work around is to add a `lock_slug` bool column to the schema. Then in your `getSlugOptions` you can do a simple check:

```
  /**
   * Get the options for generating the slug.
   * @return SlugOptions
   */
  public function getSlugOptions() : SlugOptions
  {
      $baseOptions = SlugOptions::create()
          ->generateSlugsFrom('title')
          ->saveSlugsTo('slug');

      if ($this->lock_slug) {
        $baseOptions->doNotGenerateSlugsOnUpdate();
      }

      return $baseOptions;
  }
```

In my case I just need updates disabled - for now - but you could disable on create similarly from what I've seen. You would just have to account for how to define and set lock_slug on the entity. In my case I can live with that being a toggle value.

However if you need that value to be more dynamic in nature you have to be careful relying on the HasSlug trait since AFAIK Laravel doesn't have any sort of priority mechanism to model events. So you can't reliably hook into - `creating` or `updating` the same way this package does in a reliable way to know you'll always be hooking in before/after.

**Comment by msonowal** [comment]
I have also done a similar implementation but just not satisfied enough myself, so maybe we can have some more spatie way 😊

**Comment by mallardduck** [comment]
I would absolutely agree with this sentiment too!:
> not satisfied enough myself, so maybe we can have some more spatie way

If they're willing to - one thing that comes to mind would be them decoupling the Slug generation logic from Laravel (and it's DB) specific code. Then this package would implement the more general one.

They've done a similar concept with their [spatie/menu](https://github.com/spatie/menu) and [spatie/laravel-menu](https://github.com/spatie/laravel-menu) projects. However it maybe overkill to split it into 2 packages, rather than another option; since untimely the slug is being assembled by Laravel's string helper

I'm excited to see what thoughts their team may have on some adjustments that make these kinds of things more simply accessible.
