### ISSUE TITLE
generateSlugsFrom(['title', 'id']) not working

### ISSUE THREAD

**Issue by jwarnox** [spatie/laravel-sluggable#62]
Hello Spatie,

I have in My Model:

```
public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom(['title', 'id'])
            ->saveSlugsTo('slug');
    }
```

But I get back:

```
{
"owner_id": 1,
"title": "Test Post",
"summary": "Test post summary",
"slug": "test-post",
"updated_at": "2018-02-01 23:29:07",
"created_at": "2018-02-01 23:29:07",
"id": 17
}

```

shouldn't the slug be test-post-17 ? Why is it not appending the id onto the title attribute?

regards,
Jamie

**Comment by TVke** [comment]
Hello @jwarnox 

I tested and found that the problem lies in how you save to the model.

When you set the id specifically it will have the correct behaviour and use the id in the slug. 
When the id is not set, it will send a NULL value which returns a empty string in a slug. 

hope this clarifies the problem.

regards,
Thomas

**Comment by jwarnox** [comment]
@Thomas,

Great, make perfect sense, also, great Laravel module by the way!

Thanks,
Jamie
